name: Dynamic Readme
description: Dynamically update READMEs 
inputs:
  github_token:
    required: true
    description: "The secrets GITHUB_TOKEN"

runs:
  using: "composite"
  steps:
    - name: "💾  Github Repository Metadata"
      uses: varunsridharan/action-repository-meta@main
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}

    - name: "💫  VS Utility"
      uses: varunsridharan/action-vs-utility@main

    - name: "⚡ Repository - Before Hook"
      shell: bash
      run: |
        echo " "
        if [ -f $VS_BEFORE_HOOK_FILE_LOCATION ]; then
          echo "✅ Before Hook File Found : $VS_BEFORE_HOOK_FILE_LOCATION"
          sh $VS_BEFORE_HOOK_FILE_LOCATION
        else
          echo "⚠️ No Before Hook File Found : $VS_BEFORE_HOOK_FILE_LOCATION"
        fi
        echo " "

    - name: "💫  Update README.md"
      uses: "varunsridharan/action-dynamic-readme@main"
      with:
        GLOBAL_TEMPLATE_REPOSITORY: thoughtbot/templates
        files: |
          README.md
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}

    - name: "⚡ Repository - After Hook"
      shell: bash
      run: |
        echo " "
        if [ -f $VS_AFTER_HOOK_FILE_LOCATION ]; then
          echo "✅ After Hook File Found : $VS_AFTER_HOOK_FILE_LOCATION"
          sh $VS_AFTER_HOOK_FILE_LOCATION
        else
          echo "⚠️ No After Hook File Found : $VS_AFTER_HOOK_FILE_LOCATION"
        fi
        echo " "
