name: trigger-dynamic-security-update

on:
  push:
    branches:
      - main
    paths:
      - templates/security.md

jobs:
  trigger-workflow-dispatch:
    permissions:
      actions: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository:
          - thoughtbot/testing-reusable-workflow
    steps:
      - name: Trigger Dynamic SECURITYs to be updated with templates
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: update_security-file
          repo: ${{ matrix.repository }}
          token: ${{ secrets.PAT_TOKEN }}
          ref: "main"
