name: trigger-dynamic-security-update

on:
  push:
    branches:
      - main
    paths:
      - templates/security.md

jobs:
  trigger-workflow-dispatch:
    permissions:
      actions: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository:
          - thoughtbot/administrate
          - thoughtbot/appraisal
          - thoughtbot/art_vandelay
          - thoughtbot/aws-sns-sentry-delivery
          - thoughtbot/bamboo_phoenix
          - thoughtbot/belt
          - thoughtbot/bourbon
          - thoughtbot/bourbon.io
          - thoughtbot/brakeman-linter-action
          - thoughtbot/capybara_accessibility_audit
          - thoughtbot/capybara_discoball
          - thoughtbot/clearance
          - thoughtbot/clearance-i18n
          - thoughtbot/climate_control
          - thoughtbot/cloudformation-terraform-state-backend
          - thoughtbot/croutons
          - thoughtbot/Curry
          - thoughtbot/design-sprint-guide
          - thoughtbot/design-system
          - thoughtbot/dotfiles
          - thoughtbot/ember-cli-rails
          - thoughtbot/eslint-config
          - thoughtbot/factory_bot
          - thoughtbot/factory_bot_rails
          - thoughtbot/fake_stripe
          - thoughtbot/fishery
          - thoughtbot/flightdeck
          - thoughtbot/form_props
          - thoughtbot/gold_miner
          - thoughtbot/griddler
          - thoughtbot/griddler-sendgrid
          - thoughtbot/guides
          - thoughtbot/high_voltage
          - thoughtbot/humid
          - thoughtbot/laptop
          - thoughtbot/opentelemetry-ruby
          - thoughtbot/paperback
          - thoughtbot/parity
          - thoughtbot/paul_revere
          - thoughtbot/props_template
          - thoughtbot/rcm
          - thoughtbot/react-native-on-rails
          - thoughtbot/resolved
          - thoughtbot/ruby-science
          - thoughtbot/select-your-own-seat-superglue
          - thoughtbot/shoulda
          - thoughtbot/shoulda-context
          - thoughtbot/shoulda-matchers
          - thoughtbot/stylelint-config
          - thoughtbot/superglue
          - thoughtbot/suspenders
          - thoughtbot/templates
          - thoughtbot/terraform-alb-ingress
          - thoughtbot/terraform-aws-databases
          - thoughtbot/terraform-aws-google-sso
          - thoughtbot/terraform-aws-iam-permission-sets
          - thoughtbot/terraform-aws-secrets
          - thoughtbot/terraform-aws-sentry-dsn
          - thoughtbot/terraform-aws-ses-smtp-credentials
          - thoughtbot/terraform-eks-cicd
          - thoughtbot/terraform-flightdeck-aws-application
          - thoughtbot/terraform-route-53-delegated-subdomain
          - thoughtbot/terraform-s3-bucket
          - thoughtbot/terraform-ses-domain-identity
          - thoughtbot/terrapin
          - thoughtbot/testing-reusable-workflow
          - thoughtbot/upcase
          - thoughtbot/yuri-ita
    steps:
      - name: Trigger Dynamic SECURITYs to be updated with templates
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: updatesecurity
          repo: ${{ matrix.repository }}
          token: ${{ secrets.PAT_TOKEN }}
          ref: "main"
